import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import DynamicProvider from "@/components/dynamic-provider";
import NavBar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-background">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <DynamicProvider>
            <div className="relative flex min-h-screen flex-col">
              <NavBar />
              <main className="flex-1">{children}</main>
            </div>
          </DynamicProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
